# Generated by Django 3.1 on 2021-03-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
                ('cedula', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=40)),
                ('placa', models.CharField(max_length=10)),
                ('numero_interno', models.CharField(max_length=10)),
                ('pasajeros_de_viaje', models.CharField(max_length=200)),
                ('cedula_de_pasajeros', models.CharField(max_length=200)),
            ],
        ),
    ]
